### PR TITLE
fixed remaining utf8 files -> cp1252

### PR DESCRIPTION
**Pull request by escalonn**
Figured out a way to test for this issue. (Many non‑cp1252 files are accidentally valid cp1252, just because all but like 6 bytes out of 256 are mapped) If you take a bunch of non‑ASCII chars defined in CP1252, save them as UTF8, and then open that file again in CP1252, it looks like this

http://pastebin.com/hdwy8TrG

(i.e. if you save the top line as UTF-8, then open the result in CP1252, it looks like the bottom line.) If you think about how most of those characters are going to be 2 bytes in UTF-8, it makes sense you’d see a lot of the same character interleaved with different characters, if that makes sense. Anyway

I just looked for any of those patterns in any file. Found three more. The matches were only in comments, which means there’s no issues today, but if you opened up one of those files to edit, your editor would probably guess it’s UTF8, and then you’d have trouble after you saved your work.

### CODE REVIEW

**Comment by thefinestsieve** [comment]
The defines files are supposed to be UTF.

**Comment by escalonn** [comment]
Ah. What about map/default.map? (Yes this is not in EMF)

**Comment by zijistark** [comment]
@escalonn Regarding the analysis, yes, that makes perfect sense regarding the typical pattern one would see due to conversion from UTF-8. :+1:

@thefinestsieve Are you sure they're not just being allowed to be UTF-8 characters by a lazy decoder?  I'm rather sure that there should be no UTF-8 in *all* CK2 text files, period. In this case, it should make no difference, practically speaking.

**Comment by zijistark** [comment]
@escalonn Stop working on things that aren't EMF! Aside from that, no, map/default.map is no exception to the cp1252 rule.

**Comment by thefinestsieve** [comment]
Actually, it looks like I was mistaken. I could've sworn the defines.lua file was in UTF-8, but checking back I find ANSI for the last three versions of it. Still, I know it is sensitive to having its encoding messed with, so we probably should get it back to matching the vanilla encoding.

**Comment by escalonn** [comment]
lol, i just finished the undo commit before checking for comments

**Comment by thefinestsieve** [comment]
And my work here is done... Sowing the seeds of chaos wherever I go!

**Comment by zijistark** [comment]
Leave defines.lua alone, solely because the difference doesn't matter and will just get re-merged the next time I'm integrating a compatch (or comparing to vanilla generally).

**Comment by escalonn** [comment]
well hell, the more commits there are the more useful work we’re doing, eh?

**Comment by zijistark** [comment]
@escalonn Yeah, that's pretty much my philosophy.

**Comment by escalonn** [comment]
Too bad you accepted, I was looking forward to dropping a nice "revert: revert: undo" turd on the history.

**Comment by thefinestsieve** [comment]
@zijistark already dirtied up the place enough by letting a UTF-8 localization file through... And it was tagged EMF and everything. Horrifying!

**Comment by escalonn** [comment]
@zijistark @thefinestsieve reason I've had my nose in the localisations is I'm working on an update (rewrite) for SED… if SWMH update isn't delayed, it'll probably be done shortly after that.

**Comment by zijistark** [comment]
@escalonn Sent you a PM on ParadoxPlaza. We can talk about SED & the SWMH update & stuff on Google Hangouts, in the infamous HIP group chat.

**Pull request merged**
