### PR TITLE
Brought over remaining PB decisions and PB's version of vanilla trait files

### PR DESCRIPTION
**Pull request by thefinestsieve**
I also added comments and reordered some things so they'll be slightly easier to merge in the future. Also: What is the point of the marriage decisions? Does anyone use them? I know I never have.

### CODE REVIEW

**Comment by zijistark** [comment]
Marriage decisions: I've never used them. They are Meneth's work, and they've been there a long time. They're for marrying your courtiers to each other for some reason. Apparently some people do use them, though, as they come up occasionally. Also, it's a useful answer to anybody coming from CK2+ where courtiers automatically marry each other. They expect that breeding more courtiers is a good idea or something.

**Comment by Meneth** [comment]
Some person asked for them at some point. I think they said they were something they missed for CK2Plus.

No idea how many people actually use the decisions though.

**Comment by zijistark** [comment]
Enough people use the marriage decisions for people to have complained about them improperly marrying some folks awhile back. I think that was when Meneth took advantage of the new ````can_marry = CHAR```` trigger. Also, I recommended them to somebody asking why all their courtiers never married (presumably coming from CK2Plus or maybe AGOT-- don't know about the latter) not but a month ago, so I'd say people definitely use them. I can understand the appeal too, if only I could erase all memories of the court size penalty to fertility.

**Comment by thefinestsieve** [comment]
The court size penalty is difficult enough when I'm trying to run my eugenics program. I couldn't imagine ever purposefully marrying courtiers off. As it stands, I'm still planning on putting together a targeted decision based feature to let you banish unwanted courtiers to AI courts, because I've been wanting a little more court control for ages now...

**Pull request merged**
