### PR TITLE
fix emf_nwo.csv encoding, utf8->cp1252

### PR DESCRIPTION
**Pull request by escalonn**
Quickly scanned through EMF localisations, didn’t see any other file with the problem.

### CODE REVIEW

**Comment by zijistark** [comment]
I surrender all my pride before you, for I am no longer *Ziji the Hammer* but shall instead now be known as *Stark the Ill-Ruler*.

:pensive:

:bow:

**Comment by zijistark** [comment]
... Though it's still cool if anybody wants to call me *the Hammer* and make *Hammertime* references.

**Comment by thefinestsieve** [comment]
Time to start up that sweet, sweet claimant faction.

**Comment by zijistark** [comment]
Oh, that didn't take long! It sees my spymaster has presented me four possible solutions for this faction leader:

A. Blackmail König AnaxXiphos
B. Obligate König AnaxXiphos
C. Threaten König AnaxXiphos
D. Leave him alone

**Pull request merged**
